### ISSUE TITLE
Changing font size?

### ISSUE THREAD

**Issue by esauvisky** [flozz/nautilus-terminal#10]
_Never heard of this extension before, it's awesome! Thanks for your work._

Though, is it possible to change the font size? It's a bit big for me, and there's no option to change it in dconf. If it's easy to implement, I'd be perfectly fine with making changes to the source and recompiling it as well. :)

Thanks

**Comment by flozz** [comment]
Hello,

I have no time to implement options now, but you can of course modify the source code.

It should work if you insert this:

```python
```

after `nautilus_terminal.py:174`: https://github.com/flozz/nautilus-terminal/blob/master/nautilus_terminal/nautilus_terminal.py#L174

**Comment by flozz** [comment]
→ released in v3.5.0
