### ISSUE TITLE
Installed on Ubuntu 18.04 but cannot find it in directories nor does run when hitting f4

### ISSUE THREAD

**Issue by thedonquixotic** [flozz/nautilus-terminal#15]
Hi, sorry to bother. A couple of weeks ago I inquired about this extension and I was having trouble installing the python dep required to run pip and install it. I followed the instructions and today finally remembered to actually run the commands to install it etc. It says that it has been installed. But when I check /usr/share/nautilius-extensions I see see all my other extensions, but I don't see it. And when I hit f4 nothing happens. 

Any advice on what could be wrong or how I could provide you with more information to make it possible to solve this?

**Comment by thedonquixotic** [comment]
@flozz Hi, yes I have the nautilius Python extension installed. You told me to install it on my previous issue logged. And I installed it. I still can't get it to function. Running pip etc installs nautilius terminal but I can't actually get nautilius terminal to activate or become visible.

**Comment by thedonquixotic** [comment]
I realize I am in root here but this is the same readout I got earlier when doing it under my normal shell. 

```
root@lovelace:/usr/share# sudo apt install python-nautilus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-nautilus is already the newest version (1.1-6).
The following packages were automatically installed and are no longer required:
  libkeybinder-3.0-0 pastebinit peruse-common qml-module-org-kde-kirigami
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@lovelace:/usr/share# pip install nautilus_terminal
The directory '/home/david/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/david/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: nautilus_terminal in /usr/local/lib/python2.7/dist-packages (3.2.2)
Requirement already satisfied: psutil~=5.2.2 in /usr/local/lib/python2.7/dist-packages (from nautilus_terminal) (5.2.2)
root@lovelace:/usr/share# sudo -H pip install nautilus_terminal
Requirement already satisfied: nautilus_terminal in /usr/local/lib/python2.7/dist-packages (3.2.2)
Requirement already satisfied: psutil~=5.2.2 in /usr/local/lib/python2.7/dist-packages (from nautilus_terminal) (5.2.2)

```

**Comment by thedonquixotic** [comment]
Just checked .cache http and that folder doesn't exist.

**Comment by flozz** [comment]
Does the `/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py` file exists ?

* If no: try to copy it manually: `sudo cp /usr/local/lib/python2.7/dist-packages/nautilus_terminal/nautilus_terminal_extension.py /usr/share/nautilus-python/extensions/` (note: I wrote the path by memorie, maybe you will have to fix it ^^')

* If yes, do you restarted Nautilus? (`nautilus -q`)

**Comment by thedonquixotic** [comment]
Bingo! It works! I wonder why it didn't copy over the times I kept running the install thing etc. Anyway, thanks!

**Comment by Neur1n** [comment]
Hello, I've tried everything on this page but I still could not get it working. I'm using Ubuntu 16.04 and (built-in) Python 3.5. Can it work in such environment? Thanks.
