### ISSUE TITLE
[Suggestion] Clear terminal when changing directory

### ISSUE THREAD

**Issue by l-deniau** [flozz/nautilus-terminal#16]
I think that it would be great if the terminal is clean (clear command or Ctrl + l shortcut) every time the directory is changed with the auto cd.
It shouldn't be the default behavior in my opinion, but a nice feature in the configuration.

**Comment by unknownuser88** [comment]
+1

**Comment by Barben360** [comment]
+1. And I even think this could be default.

**Comment by GerdHel** [comment]
+1. I would also appreciate it a lot. Some undesired behavior might occur when you enter a command and the auto cd is added in the end. It ended up in deleting the wrong files in the wrong folder by accident.

**Comment by vesterlay** [comment]
+1

**Comment by flozz** [comment]
Implemented by PR #55. It will be released by the end of the month :)
