### ISSUE TITLE
Add --user to pip command in README

### ISSUE THREAD

**Issue by jhe-** [flozz/nautilus-terminal#22]
When executing `pip install nautilus_terminal`, I get the error:

`Permission denied: '/usr/local/lib/python2.7/dist-packages/nautilus_terminal-3.2.2.dist-info'`

It should be mentioned in the readme that the `--user` option is required. Older versions of pip also lack an informative error message, whereas 18.1 at least tells me this.

---
Thank you for making this great extension!

**Comment by flozz** [comment]
I added the `--user` option in the README, thanks for the suggestion ;)
