### ISSUE TITLE
[Ubuntu] Install Usability

### ISSUE THREAD

**Issue by fkraemer** [flozz/nautilus-terminal#26]
It took me about two hours, trying to make sense of the non-existant install-debug-output, where I was trying to:
-install globally (sudo pip install nautilus_terminal)
-install locally (pip install nautilus_terminal)
-install from source both globally and locally
with nothing appearing in nautilus/dconf-editor

And then, when opening a new issue, the github find produces: https://github.com/flozz/nautilus-terminal/issues/15, --> I was just missing "python-nautilus" as installed packages.
So, as a suggestion to spare other users time:
-Could this prerequisite be checked during installation?
-Otherwise: could a Ubuntu section be added in the README install section to make this prerequisite more prominent?

**Comment by flozz** [comment]
The work on the Debian package is in progress → https://github.com/flozz/nautilus-terminal/tree/debian-package/debian

It will probably be available tomorrow :)

**Comment by flozz** [comment]
The debian package is released and available through a PPA. The donc is here:

https://github.com/flozz/nautilus-terminal#from-the-ppa-ubuntu

:)
