### ISSUE TITLE
Allow the terminal to be hidden by default

### ISSUE THREAD

**Issue by achadwick** [flozz/nautilus-terminal#3]
Please can nautilus-terminal be configured to not show by default for new windows? I ask because I use the keyboard to get around in Nautilus, but the terminal eats its focus and you can't press <kbd>Tab</kbd> to get out. Instead I have to remember to press <kbd>F4</kbd> for \*every\* new window, which is annoying. Normally I only want the terminal briefly, for running "make" or something similar.

I don't care how it's done, but the workflow should be natural. To me there's a couple of options:

1. the terminal's hide/show state could be stored in a setting between sessions.
2. Instead, give the extension a context menu and put an entry+action  there.

**Comment by flozz** [comment]
Hello,

Having the terminal always opened is boring for mee too. I have to implement settings in Nautilus Temrinal to allow hiding the terminal by default, automatically opening it for certain folder (based on a folder list, or as you suggested, from an history of previous browsing sessions),...

**Comment by achadwick** [comment]
For me, it's simplest to just remember the on/off state. Making it a per-folder setting might be confusing.

I've just realized I would be happy if the terminal was on by default (use case: you want to show new users what it looks like immediately!) but if on/off was a sticky, global setting that applied to new windows.

Potential problem: some folders are virtual, and nautilus-terminal hides and shows the terminal for these already. Having two reasons to hide and show a terminal might be confusing too.

Perhaps the widgets could be structured like this:

    Gtk.Stack    # controlled by `(not virtual) or in_use`
      page1: the current VTK terminal
      page2: styled Gtk.Label "Cannot use terminal here"

Then you might change the stack page depending on the browse state and terminal state.

**Comment by flozz** [comment]
Hello,

I am currently working on the settings (using GSettings) on the [implements-settings](https://github.com/flozz/nautilus-terminal/blob/implements-settings/nautilus_terminal/schemas/org.flozz.nautilus-terminal.gschema.xml) branch.

I do not know if I will make an UI for it right now, but it will be editable at least with `dconf-editor`

**Comment by flozz** [comment]
Settings available in **v3.2.0**:

https://github.com/flozz/nautilus-terminal#configuring
