### ISSUE TITLE
Change colors?

### ISSUE THREAD

**Issue by lupont** [flozz/nautilus-terminal#32]
Hello!
Lovely extension, I use it daily. However, since I use a light theme, the black terminal stands out a bit. Is there any way to change the background/font colors? 

Thanks!

**Comment by giedriusStan** [comment]
I'm not a python developer, but I tried to change the background myself. Anybody know why this line of code wouldn't work?
self._ui_terminal.set_color_background(Gdk.RGBA(64,69,82))

**Comment by flozz** [comment]
Hello,

@lupont sorry I completely forget about this issue... I do not implemented a way to configure color (lack of time...)

@giedriusStan try passing 4 numbers between 0 and 1: `Gdk.RGBA(64/255.0, 69/255.0, 82/255.0, 1)`

**Comment by giedriusStan** [comment]
> @giedriusStan try passing 4 numbers between 0 and 1: `Gdk.RGBA(64/255.0, 69/255.0, 82/255.0, 1)`

OMG it worked :) Thanks!

If anyone else wants to achieve this, add this line to _build_and_inject_ui function

`self._ui_terminal.set_color_background(Gdk.RGBA(64/255.0, 69/255.0, 82/255.0, 1))`

**Comment by lhmngwy** [comment]
If anyone is interested, I added the following to the "_build_and_inject_ui" function to match the "Tango" theme on Ubuntu 20.04:
`self._ui_terminal.set_colors(Gdk.RGBA(211/255.0, 215/255.0, 207/255.0, 1), Gdk.RGBA(56/255.0, 12/255.0, 42/255.0, 1), [Gdk.RGBA(0/255.0, 0/255.0, 0/255.0, 1), Gdk.RGBA(204/255.0, 0/255.0, 0/255.0, 1), Gdk.RGBA(78/255.0, 154/255.0, 6/255.0, 1), Gdk.RGBA(196/255.0, 160/255.0, 0/255.0, 1), Gdk.RGBA(52/255.0, 101/255.0, 164/255.0, 1), Gdk.RGBA(117/255.0, 80/255.0, 123/255.0, 1), Gdk.RGBA(6/255.0, 152/255.0, 154/255.0, 1), Gdk.RGBA(211/255.0, 215/255.0, 207/255.0, 1), Gdk.RGBA(85/255.0, 87/255.0, 83/255.0, 1), Gdk.RGBA(239/255.0, 41/255.0, 41/255.0, 1), Gdk.RGBA(138/255.0, 226/255.0, 52/255.0, 1), Gdk.RGBA(252/255.0, 233/255.0, 79/255.0, 1), Gdk.RGBA(114/255.0, 159/255.0, 207/255.0, 1), Gdk.RGBA(173/255.0, 127/255.0, 168/255.0, 1), Gdk.RGBA(52/255.0, 226/255.0, 226/255.0, 1), Gdk.RGBA(238/255.0, 238/255.0, 236/255.0, 1)])`

**Comment by flozz** [comment]
The background and the text color are now configurable. Available on `master`, I will release this soon.

**Comment by flozz** [comment]
→ released in v3.4.0 :)
