### ISSUE TITLE
Where does INSIDE_NAUTILUS_TERMINAL env variable come from?

### ISSUE THREAD

**Issue by jfunction** [flozz/nautilus-terminal#34]
I was trying to find a way to execute code in bashrc only if we are in the nautilus terminal. To this end I did `env|sort|uniq>somefile` in my terminal and in the nautilus terminal and after doing a `diff` I found an environment variable called `INSIDE_NAUTILUS_TERMINAL` was set and empty inside the nautilus terminal but not in my own terminal. 

After searching the source code on github, as well as various locations on my PC, I can not find references to this `INSIDE_NAUTILUS_TERMINAL` anywhere. I skimmed the source code and even did an `strace nautilus` to see if it was maybe coming from a config or something but I still came up short. Where does it come from? How is it being set?

I realise my approach to solving my original problem - how to execute code only on initial invocation of the nautilus terminal - is probably not the best one. So another question is how should I go about that? 

Also thank you for the plugin, I'm enjoying it!

**Comment by flozz** [comment]
Hello,

> skimmed the source code and even did an strace nautilus to see if it was maybe coming from a config or something but I still came up short. Where does it come from? How is it being set?

I think you mean `INSIDE_NAUTILUS_PYTHON` and not `INSIDE_NAUTILUS_TERMINAL`. 😉️

This variable is set by the Nautilus Python plugin: https://gitlab.gnome.org/GNOME/nautilus-python/blob/master/src/nautilus-python.c#L195

> I realise my approach to solving my original problem - how to execute code only on initial invocation of the nautilus terminal - is probably not the best one. So another question is how should I go about that?

Currently, it is probably the only solution as I do not implemented anything for this. 😅️

**Comment by jfunction** [comment]
Ah :man_facepalming: I see now. Thank you!

In case it can help someone, the PS1 prompt was messed up so I used http://bashrcgenerator.com/ to make a new one and did this in my bashrc: 
```[bash]
if [[ -n "`env|grep INSIDE_NAUTILUS_PYTHON`" ]]; then
    export PS1="\[\033[38;5;8m\]{\[$(tput sgr0)\]\[\033[38;5;187m\]\A\[$(tput sgr0)\]\[\033[38;5;8m\]}\[$(tput sgr0)\]\[\033[38;5;1m\]\$?\[$(tput sgr0)\]\[\033[38;5;8m\]>\[$(tput sgr0)\]\[\033[38;5;115m\]\u\[$(tput sgr0)\]\[\033[38;5;8m\]@\[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;38m\]\h\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;8m\]:\[$(tput sgr0)\]\[\033[38;5;9m\]\W\[$(tput sgr0)\]\[\033[38;5;8m\]\\$\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"
    echo "Nautilus Plugin"
fi
```

Anyway, thanks again :+1:
