### ISSUE TITLE
No release file for Eoan

### ISSUE THREAD

**Issue by Ace-Cassidy** [flozz/nautilus-terminal#36]
E: The repository 'http://ppa.launchpad.net/flozz/nautilus-terminal/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by flozz** [comment]
The packages on the PPA are no more up to date. I have to build new ones but I have currently no time to do it.

You can install nautilus-terminal using pip:

    sudo pip install nautilus_terminal

Then quit nautilus:

    nautilus -q

and it should work
