### ISSUE TITLE
Disable/hide by default

### ISSUE THREAD

**Issue by TomaszGasior** [flozz/nautilus-terminal#37]
In my honest opinion "default-show-terminal" setting should default to "false" instead "true".

Rationale:

* Terminal widget steals focus. It's good when widget visibility is invoked manually by the user using F4 key but it's very bad for UX when focus is stolen in each new window of Nautilus. Basically Nautilus is unusable with for keyboard oriented users with your extension installed. Of course I can change "default-show-terminal" setting using dconf-editor but I think safe defaults should be important for Nautilus extensions the same way as for official  GNOME software. :)
* nautilus terminal may be installed system-wide but only some users may want to use it's by default. Having to implicitly enable "default-show-terminal" will make the terminal hidden for new users who may not need it.
* Your extension should not considered stable as I understand from README. It's bad idea to show unstable software by default. :)

**Comment by flozz** [comment]
Hello,

I understand that for a system-wild install on a shared computer, this can be an issue. But if the terminal is hidden by default when Nautilus is restarted, I'm afraid people think it is broken... 

Thanks for your suggestion, I will think about this :)

**Comment by TomaszGasior** [comment]
For me it's intuitive to revert to default state in newly created window. But, for some users, it might be good idea to save last state as separate setting (or cache file) and restore it in next Nautilus window, although I prefer current behaviour, reverting.

**Comment by flozz** [comment]
When I said "when Nautilus is restarted" I mean the first time it is restarted after installing Nautilus Terminal :)

**Comment by TomaszGasior** [comment]
Okaay. The best way to solve this issue is to add new command in Nautilus main menu — "Show/hide terminal". Is there any API for this? Probably no…

**Comment by flozz** [comment]
No, only in the contextual menu if my memory is good... But there is probably a way to workaround this... #OneMoreHack xD

**Comment by flozz** [comment]
I close this issue as it is quite old and it is partially resolved:

* The "stealing focus" point (that was very annoying) is solved by #54 
* I still think the terminal should be displayed by default to allow users to see it works. For multi-user computers, Nautilus Terminal could also be installed on a per-user basis instead of system wild :)
