### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by TomaszGasior** [flozz/nautilus-terminal#38]
I am packaging your extension for Fedora on COPR server. Maybe you can update your README to point Fedora users to my package. 

```
dnf copr enable tomaszgasior/mushrooms
dnf install nautilus-terminal
```

I have one downstream patch for https://github.com/flozz/nautilus-terminal/issues/37

Feel free to close this issue if you are not interested in. :)

More information:
* https://copr.fedorainfracloud.org/coprs/tomaszgasior/mushrooms/package/nautilus-terminal/
* https://github.com/TomaszGasior/mushrooms-rpms/tree/nautilus-terminal

**Comment by flozz** [comment]
Thank you, I added info about your Fedora package in the README :)
