### ISSUE TITLE
Where does nautilus terminal get the font from ?

### ISSUE THREAD

**Issue by danielrivgw** [flozz/nautilus-terminal#39]
I'd like to know where does Nautilus Terminal gets the font from, thanks

**Comment by flozz** [comment]
As Nautilus Terminal does not set the font, the system's (GNOME/GTK) default monospace font should be used.

You can configure it with GNOME Tweak Tool:

![Screenshot: Font config in GNOME Tweak Tool](https://user-images.githubusercontent.com/971438/75235855-33570d80-57bd-11ea-89a9-e247f896b851.png)
