### ISSUE TITLE
File DnD into the terminal widget does not set keyboard focus

### ISSUE THREAD

**Issue by achadwick** [flozz/nautilus-terminal#4]
If I drag a file into the terminal section, my fingers want to start typing again. Often I just want to press <kbd>Return</kbd> to issue a command on a single file.

However, keyboard focus is transferred _out_ of the terminal at the start of a drag from the main graphical files view. I can't just start typing after the drag and be happy :sweat_smile: 

When a file drag finishes inside the terminal window, after the text is inserted, could keyboard focus be applied to the terminal widget please?

**Comment by flozz** [comment]
Yep, it is a good idea :D
