### ISSUE TITLE
Not able to lauch by F4

### ISSUE THREAD

**Issue by devprabal** [flozz/nautilus-terminal#42]
I installed using
 `pip3 install --user nautilus_terminal`
It got installed in `~/.local/lib/python3.8/site-packages`
I also did the workaround 
`sudo tools/update-extension-user.sh install`
by cloning the repo to `~`
But I cannot activate the terminal by pressing Fn+F4

**Comment by flozz** [comment]
Hello, as you installed it using `pip3` you have to install `python3-nautilus`:

    sudo apt install python3-nautilus

Then restart nautilus:

    nautilus -q && nautilus

for more information, please read the issue #41 :)

**Comment by devprabal** [comment]
Yes, this fixes the issue!! Thanks for such a nice feature in nautilus!
