### ISSUE TITLE
Change Shortcuts

### ISSUE THREAD

**Issue by DATL4G** [flozz/nautilus-terminal#43]
### Is it possible to change the shortcuts?

In my normal terminal e.g. I changed the shortcuts to copy and paste, however this setting isn't present in this nautilus-terminal.

(Installed with python)

Pop!_OS 20.04 LTS
Linux 5.4.0-7626-generic
Gnome 3.36.1

**Comment by flozz** [comment]
The shortcut is hard-coded so it is not configurable yet...

If you really want to change it, you have to edit nautilus_terminal.py:306:

* https://github.com/flozz/nautilus-terminal/blob/master/nautilus_terminal/nautilus_terminal.py#L306

But you are right, it could be nice to be able to configure this.

**Comment by flozz** [comment]
This is now configurable. The code is on `master`, it will be released soon.

**Comment by flozz** [comment]
→ released in v3.4.0 :)
