### ISSUE TITLE
Auto cd from the embeded terminal to the nautilus

### ISSUE THREAD

**Issue by Sassoon-Mao** [flozz/nautilus-terminal#44]
the nautilus-terminal works very well in my laptop :

------------------ 
OS: Arch Linux x86_64 
Host: 80GQ Lenovo S40-70 
Kernel: 5.6.11-arch1-1 
Uptime: 18 hours, 21 mins 
Packages: 1041 (pacman) 
Shell: fish 3.1.2 
Resolution: 1366x768 
DE: GNOME 
WM: Mutter 
WM Theme: Mojave-light 
Theme: Mojave-light [GTK2/3] 
Icons: la-capitaine-icon-theme [GTK2/3] 
Terminal: guake 
CPU: Intel i3-4030U (4) @ 1.800GHz 
GPU: Intel Haswell-ULT 
GPU: AMD ATI Radeon HD 8550M / R5 M230 
Memory: 2420MiB / 3845MiB 
******************************************************************
and the features do satisfy my need, especially the one as you said,
> Follow the navigation: if you navigate in Nautilus, the cd command is automatically executed in the terminal,

Here, i would like to put up a suggestion, 
*  **Follow the navigation: if you change directory in the embeded terminal, the nautilus is automatically navigating.**

before immersing in Gnome, i used KDE/Plasma for a while, it seems the dolphin supports naturally the two features above. 

- [x] : first issue on github.com.

**Comment by flozz** [comment]
Hello,

It is a good idea, but it seems to be very difficult to do as there is no API in Nautilus to change its current directory from an extension. I let you read the issue #21 for more information.

I close this issue as this feature have already been asked in #21. 

Thank you for your report :)
