### ISSUE TITLE
Is this an early developer version? - inclusion in Solus

### ISSUE THREAD

**Issue by JacekJagosz** [flozz/nautilus-terminal#47]
I wanted to include this in the Solus repos, but it can't be accepted because in the readme it says:

> NOTE²: This is an early development version, some feature are missing (see below).

So do you still consider this experimental or can this be considered stable?
[Link to the discussion](https://dev.getsol.us/T8969)

**Comment by flozz** [comment]
Hello,

Sadly, there still be stability issues. Currently Nautilus Terminal can causes random Nautilus crashes, especially when toggling the `show hidden files` option (see #46). :(

**Comment by JacekJagosz** [comment]
Thanks for clarifying that, when you manage to get it stable I will try to get it to main Solus repos as quickly as possible.
On my side it hasn't caused a single problem in half a year of using it, so still an amazing job!

**Comment by flozz** [comment]
I am not sure I will be able to make it 100% stable, but who knows :)

I close this issue as the question is answered :)

**Comment by JacekJagosz** [comment]
If you someday manage to fix the problematic bugs, could you write "I consider it stable" or "I no longer consider this an early development version" so this can be accepted into Solus repos.

**Comment by flozz** [comment]
yes of course :)
