### ISSUE TITLE
Please add dconf-options for change background/text color, and font for terminal UI

### ISSUE THREAD

**Issue by toanphuong** [flozz/nautilus-terminal#48]
Great extension!

Please add dconf options for change background/text color, and font for terminal UI.

Thanks in advance!

**Comment by flozz** [comment]
Hello,

I have no time to work on this currently, but I will try to do something once I released [Rivalcfg v4.0](https://github.com/flozz/rivalcfg).

Meanwhile, you can look at the following issue that proposes solutions to change the font and the colors by editing the sources of this software:

* https://github.com/flozz/nautilus-terminal/issues/32
* https://github.com/flozz/nautilus-terminal/issues/10

**Comment by toanphuong** [comment]
Thanks for your support!

**Comment by flozz** [comment]
Color configuration implemented, see #32
