### ISSUE TITLE
Not working on Ubuntu 20.04.1; Dconf key not found!

### ISSUE THREAD

**Issue by anishmittal2020** [flozz/nautilus-terminal#49]
# System

```bash
$ nautilus --version
GNOME nautilus 3.36.3
```

OS: Ubuntu 20.04.1 LTS x8 
Kernel: 5.4.0-52-generic 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Unity 
WM: Mutter 
WM Theme: HighContrast 
Theme: Yaru-light [GTK2/3 
Icons: Yaru [GTK2/3] 
CPU: Intel i7-4720HQ (8)  
GPU: NVIDIA GeForce GTX 9 
GPU: Intel 4th Gen Core P 
Memory: 3664MiB / 7850MiB 

# Installation

```bash
$ sudo apt install python3-nautilus python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-nautilus is already the newest version (1.2.3-1ubuntu1).
python3-pip is already the newest version (20.0.2-5ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

$ pip3 install --user nautilus_terminal
Requirement already satisfied: nautilus_terminal in /home/nikhil/.local/lib/python3.9/site-packages (3.3.0)
Requirement already satisfied: psutil~=5.2.2 in /home/nikhil/.local/lib/python3.9/site-packages (from nautilus_terminal) (5.2.2)

$ sudo tools/update-extension-user.sh install 
'nautilus_terminal/nautilus_terminal_extension.py' -> '/root/.local/share/nautilus-python/extensions/nautilus_terminal_extension.py'
```

# Dconf Issue

```bash
$ dconf-editor /org/flozz/nautilus-terminal
```
![image](https://user-images.githubusercontent.com/42092626/98903169-58102400-24b7-11eb-9c2e-ed236f21b5b9.png)

---

# Extension not getting activated

> **Tried to activate the extension by presssing F4, but nothing happens!**

**Comment by flozz** [comment]
Hello,

The dconf schema should appear after the restart of Nautilus with Nautilus Terminal enabled. If it does not work, you may try a global install instead.

**Comment by anishmittal2020** [comment]
Global installation fixed the issue

**Comment by anishmittal2020** [comment]
Global installation fixed the issue
