### ISSUE TITLE
Very broke on Ubuntu Budgie 17.04

### ISSUE THREAD

**Issue by octoxan** [flozz/nautilus-terminal#5]
![screenshot from 2017-07-07 09 29 42](https://user-images.githubusercontent.com/4382195/27959818-f6bb04c0-62f6-11e7-9e9c-d9c17339fb55.png)

This is what I end up with no matter if I install globally or per user. Whether the terminal is hidden or not there is a ton of empty white space and all but the first 1 1/2 folders are cut off lol

**Comment by flozz** [comment]
Hello,

There is currently an issue when folders are displayed in list view, currently Nautilus Terminal only handles folders displayed in icon view.

I have to fix that, but I have no time to work on this project currently :(

**Comment by AshlessCinder** [comment]
The extra white space is happening to me as well on a fresh install of Antergos and Gnome (Antergos just an installer for Arch).

The cut off issue isn't present for me on list or icon views.
Sounds like it might be 2 separate issues.

The spacing issue doesn't appear until I switch between list and icon views (in either direction)
This happens whenever I search for a keyword in a directory though, so it's often.

The issue persists until I start a new nautilus window.

I really like this extension BTW, excellent idea. Thanks for your work :smile:

**Comment by flozz** [comment]
This issue is probably due to wrong parameters when I rebuild the Nautilus UI, I will try to fix this when I will have time :)

**Comment by flozz** [comment]
This should be solved by #11
