### ISSUE TITLE
Change open terminal shortcut

### ISSUE THREAD

**Issue by risalfajar** [flozz/nautilus-terminal#50]
I don't have function keys on my keyboard, how can I change the shortcut to open nautilus terminal?

**Comment by flozz** [comment]
I made this configurable. It is on the `master` branch. I will release this soon. :)

**Comment by flozz** [comment]
→ released in v3.4.0 :)

**Comment by risalfajar** [comment]
Nice, I can edit it from Dconf Editor now, I want to map it to CTRL+4, what value should I put on it?

**Comment by flozz** [comment]
It is [parsed by GTK](https://developer.gnome.org/gtk3/stable/gtk3-Keyboard-Accelerators.html#gtk-accelerator-parse), so it should be something like `<Ctrl>4` :)

**Comment by risalfajar** [comment]
Awesome! Thanks for this amazing work 🥳
