### ISSUE TITLE
Cannot copy from terminal and paste into on PopOS 20.10

### ISSUE THREAD

**Issue by danieltomasz** [flozz/nautilus-terminal#51]
I cannot copy and paste into  terminal, I installed system wide nautilus-terminal
`sudo pip3 install nautilus_terminal`

Is this feature present in this extension?

**Comment by flozz** [comment]
Hello,

Copy/Paste should work using `ctrl+shift+c` and `ctrl+shift+v` shortcuts :)

**Comment by danieltomasz** [comment]
Hi! Thanks for the advice! :) It works :)
