### ISSUE TITLE
Is `python3 --install-user` necessary?

### ISSUE THREAD

**Issue by raffaem** [flozz/nautilus-terminal#56]
Ubuntu 20.10. Installing from PyPI. The second command (`python3 -m nautilus_terminal --install-user`) returns an error.

```
$ pip3 install --user nautilus_terminal
[...]
$ python3 -m nautilus_terminal --install-user
/usr/bin/python3: No module named nautilus_terminal.__main__; 'nautilus_terminal' is a package and cannot be directly executed
```

The add-on works correctly nevertheless

**Comment by flozz** [comment]
Hello,

There is currently a mismatch between the instructions available in this repository and the Nautilus Terminal version available on PyPI. The documentation available on the `master` are for the next Nautilus Terminal version that is about to be released. :)

So if you installed Nautilus Terminal from PyPI this command does not exists yet and it may work out of the box :)

**Comment by raffaem** [comment]
ok understood.

Thank you :)
