### ISSUE TITLE
[QUESTION] Change focus

### ISSUE THREAD

**Issue by raffaem** [flozz/nautilus-terminal#57]
When I start nautilus, the focus will be on the terminal.

Pressing the down arrow will do nothing.

Is there a keyboard shortcut to switch the focus back to the file viewer?

I am looking for a keyboard shortcut that select the first file in the file viewer basically, so that the down arrow key will move to the next file

**Comment by flozz** [comment]
Hello,

Nautilus Terminal steals focus and that is annoying. [This have been fixed](https://github.com/flozz/nautilus-terminal/pull/54) recently and the fix will be released in the next Nautilus Terminal version (very soon!) :)

**Comment by raffaem** [comment]
Good, already fixed.

Thank you :)
