### ISSUE TITLE
User-wide installation from source doesn't work (but system-wide do)

### ISSUE THREAD

**Issue by raffaem** [flozz/nautilus-terminal#58]
I have cloned the repository and installed user-wide with:
```
pip3 install --user .
python3 -m nautilus_terminal --install-user
```

The terminal simply doesn't show up.

Debug info:
```
$ nautilus-terminal --print-debug

NAUTILUS TERMINAL
=================
Version: 3.5.0
System-wide extension: Absent
Current user extension: Installed
Installation path: /home/raffaele/.local/lib/python3.8/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.32
Version: #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021
Distribution issue: Ubuntu 20.10 \n \l

PYTHON
======
Python version: 3.8.6

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed
```

I then uninstalled. Then I installed system-wide with:
```
sudo pip3 install .
sudo nautilus-terminal --install-system
```

Now it works

**Comment by flozz** [comment]
Hello,

I am not able to reproduce. Can you try to uninstall the system-wide installation and to install it again on your user, and if it still not working, please give me the Nautilus logs.

The following command should attach Nautilus to your terminal so you can see the logs :)

    nautilus -q && nautilus

**Comment by flozz** [comment]
Hello, maybe you can have a look to #60 that may have the same issue than yours :)

**Comment by raffaem** [comment]
The command you typed exit immediately without giving any significant logs (and without opening nautilus):
```
$ nautilus -q && nautilus
Initializing nautilus-dropbox 2020.03.04
```

Just `nautilus` will open nautilus but the log is the same. However, when I close nautilus it stays open in the terminal and I have to kill it with CTRL+C.

Here are the debug info:
```
$ python3 -m nautilus_terminal --print-debug 
 
NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Absent
Current user extension: Installed
Installation path: /run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/progetti_altrui/nautilus-terminal/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.12.7-300.fc34.x86_64-x86_64-with-glibc2.33
Version: #1 SMP Wed May 26 12:58:58 UTC 2021
Distribution issue: \S
Kernel \r on an \m (\l)

PYTHON
======
Python version: 3.9.5

SYSTEM DEPENDENCIES
===================
Nautilus Python: Absent
GLib schemas compiler: Installed
```

**Comment by raffaem** [comment]
I had to install nautilus python with
```
sudo dnf install nautilus-python
```
it works now. Thank you so much for the support and for this extension :)
