### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by CSpencerND** [flozz/nautilus-terminal#59]
python3 -m nautilus_terminal --check confirms that it is indeed installed, however, I press f4 and nothing happens. Additionally, there is no flozz entry in my dconf.

**Comment by flozz** [comment]
Hello,

Can you give me the result of the following command:

```
python3 -m nautilus_terminal --print-debug 
```

**Comment by CSpencerND** [comment]
Wow. What a quick response. Thank you!

`python3 -m nautilus_terminal --print-debug `:
NAUTILUS TERMINAL
=================
Version: 4.0.0
System-wide extension: Absent
Current user extension: Installed
Installation path: /home/cspencer/.local/lib/python3.8/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.11.0-7614-generic-x86_64-with-glibc2.10
Version: #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC
Distribution issue: Pop!_OS 20.10 \n \l

PYTHON
======
Python version: 3.8.5

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed


`nautilus -q && nautilus`:
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

(org.gnome.Nautilus:196228): Nautilus-Python-WARNING **: 08:32:27.984: pygobject initialization failed

(org.gnome.Nautilus:196228): Nautilus-Python-WARNING **: 08:32:27.984: nautilus_python_init_python failed
Initializing nautilus-dropbox 2019.02.14

**Comment by CSpencerND** [comment]
Oh gosh, I forgot about this `No module named 'gi'`.
I remember having problems installing it for something else so I gave up. Time to try again.

**Comment by CSpencerND** [comment]
Ok, I got gi. New output: 
```
nautilus -q && nautilus
* Starting Nautilus Terminal
GSConnect: No translation file found for domain

```

**Comment by flozz** [comment]
It is strange that nothing happens as Nautilus Terminal starts... :thinking: 

Can you try to press `F4` to see if it displays the terminal

If it doesn't work please try to have more log with the following commands:

    export NAUTILUS_TERMINAL_DEBUG=true
    nautilus -q && nautilus

**Comment by CSpencerND** [comment]
Nope. Still no effect.

**Comment by flozz** [comment]
Can you try installing it system-wide to see if it works better? I have no idea of what could go wrong :(

**Comment by CSpencerND** [comment]
Wooooowww. That did it! Thank you so much! I _sort of_ know what the problem is. 
User install puts it in `$HOME/.local/bin`, and system install puts it in `/usr/local/bin`.
Here's the part that doesn't make sense. It seems the system wasn't reading it from `$HOME/.local/bin` even though I have other executables in there that work just fine. It's quite odd.

**Comment by flozz** [comment]
Ok, thank you for the feedback.

I will work on this this weekend; I will try to reproduce the issue and to make the user install smoother :)

**Comment by CSpencerND** [comment]
I do have one more question I haven't been able to find a good answer for. Do you know if there's any way to change the default terminal emulator for nautilus? I only find old posts with deprecated information about it. If not, don't worry about it. You've helped me enough. I appreciate you.

**Comment by flozz** [comment]
What do you mean by changing the terminal emulator?

Nautilus Terminal uses the `Vte.Terminal` GTK widget (the one that is used by GNOME Terminal, Gake, Terminator, XFCE4 Terminal, etc.). It is not possible to integrate anything else without an huge amount of work :)

**Comment by CSpencerND** [comment]
Thanks for the info :)
