### ISSUE TITLE
Can not use / 

### ISSUE THREAD

**Issue by rafaelcorsi** [flozz/nautilus-terminal#6]
Dear,

when a try to use the / on the nautilus terminal, the key is captured by nautilus and start to modify the nautilus path. So I can not use the key / on the terminal.

> Files : 3.24.2
> OS : Arch (Manjaro)
> Installed via yaourt 

all the best,
R. Corsi

**Comment by flozz** [comment]
Hello,

the [nauitlus-terminal](https://www.archlinux.org/packages/community/any/nautilus-terminal/) package from Arch repository is outdated. This issue should be solved with the latest version (but this version is experimental and have some other known issue).

If you want to try the latest version, first uninstall nautilus-terminal using pacman or yaourt, and then install it with pip:

* https://github.com/flozz/nautilus-terminal#from-pypi

Regards,

**Comment by flozz** [comment]
Hello,

I close this issue, please re(open it if you still have issues :)
