### ISSUE TITLE
v4.0.0 crashes Nautilus 40 on Ubuntu 21.04, doesn't work with Nautilus 3.36 on Ubuntu 20.4

### ISSUE THREAD

**Issue by logix2** [flozz/nautilus-terminal#60]
I'm using Nautilus Terminal 4.0.0 on Ubuntu 21.04 with Python 3.9.4, and it crashes Nautilus:

```
(org.gnome.Nautilus:774073): GLib-GIO-ERROR **: 16:59:58.634: Settings schema 'org.flozz.nautilus-terminal' does not contain a key named 'default-focus-terminal'
```

**Comment by flozz** [comment]
Hello,

can you give me the result of the following command: 

    python3 -m nautilus_terminal --print-debug 

:)

**Comment by logix2** [comment]
Sure:
```
python3 -m nautilus_terminal --print-debug 

NAUTILUS TERMINAL
=================
Version: 4.0.0
System-wide extension: Absent
Current user extension: Absent
Installation path: /home/logix/.local/lib/python3.9/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.11.0-16-generic-x86_64-with-glibc2.33
Version: #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021
Distribution issue: Ubuntu 21.04 \n \l

PYTHON
======
Python version: 3.9.4

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed
```

I also tried it on Ubuntu 20.04. It doesn't crash Nautilus, but Nautilus Terminal doesn't open.

**Comment by logix2** [comment]
By the way, in case it helps. Both of the systems I mentioned already had Nautilus Terminal (an older version, I don't remember which). So it was not a fresh install.

**Comment by logix2** [comment]
Sorry for spamming, but I forgot a very important piece of information. I've upgraded to GNOME 40 on Ubuntu 21.04, so I'm using Nautilus 40 on this Ubuntu version (for Ubuntu 20.04, on which I mentioned that it doesn't crash Nautilus, but it doesn't work either, I'm running the standard Nautilus version that ships with Ubuntu, which is 3.36).

**Comment by flozz** [comment]
It is strange that both system and user extension are not installed... I will have to check what happens.

Can you try to run the following command?

    sudo python3 -m nautilus_terminal --install-system 

It should install the extension system-wide and build the gsettings schemas as well (probably it takes a partial schema from you previous installation)

**Comment by logix2** [comment]
That doesn't work, I guess because using ``sudo`` doesn't use my home folder, where the nautilus_terminal package is installed?

```
$ sudo python3 -m nautilus_terminal --install-system 
/usr/bin/python3: No module named nautilus_terminal
```

**Comment by flozz** [comment]
Yes probably... can you try to install Nautilus Terminal system-wide... It seems there is some things to fix with the user install ^^'

**Comment by logix2** [comment]
Unfortunately I can't use sudo with pip, I already had my system broken by that a long time ago, so I stay away from it (and never recommend it either).

**Comment by flozz** [comment]
ok... As a temporary fix, try to 

* copy the [org.flozz.nautilus-terminal.gschema.xml](https://github.com/flozz/nautilus-terminal/blob/master/nautilus_terminal/schemas/org.flozz.nautilus-terminal.gschema.xml) file to `/usr/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml`
* and then run the `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/` command

I will try to fix and improve the user install :)

**Comment by logix2** [comment]
Ok, thank you!

**Comment by logix2** [comment]
Unfortunately that didn't get it to work either. Nautilus 40 no longer crashes, but Nautilus Terminal doesn't open (with either Nautilus Terminal set to automatically open on Nautilus start, or with that disabled and trying the F4 key to open it).

Side note: I do not have time to test it during the following days, maybe until around Tuesday, because I'm in the process of moving. Then I can test stuff again, and when it's fixed and it works with Nautilus 40, I'll write an article about it on [https://www.linuxuprising.com](https://www.linuxuprising.com)

**Comment by flozz** [comment]
The **v4.0.1** should fix the user install: it installs and build the GLib schema.

To clean you installation, you may:

* remove the `/usr/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml` if it exists
* recompile system schemas: `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`
* then, after installing the v4.0.1: `python3 -m nauitlus_terminal --install-user`

After a restart of Nautilus it should be ok :)

**Comment by logix2** [comment]
On Ubuntu 21.04 with GNOME 40: Just ``pip3 install --upgrade --user nautilus_terminal`` got it to work, I can now open Nautilus Terminal inside Nautilus. The ``python3 -m nauitlus_terminal --install-user`` command continues to not work though:
```
$ python3 -m nauitlus_terminal --install-user
/usr/bin/python3: No module named nauitlus_terminal
```

**Comment by flozz** [comment]
I do not know why you cannot import the module as it should be in the python path... I will try to reproduce on a VM this weekend

**Comment by flozz** [comment]
I am not able to reproduce on a fresh install of Ubuntu 21.04... It is probably more a Python environment issue than a Nautilus Terminal one :(

Are you able to call the script like this?

    ~/.local/bin/nautilus-terminal --install-user

**Comment by logix2** [comment]
Yes, that works. Thank you! So this part of the issue was due to my system. Sorry to waste your time with it.

**Comment by flozz** [comment]
No problem :)

**Comment by DATL4G** [comment]
I still have this problem on PopOS 21.04
I tried everything according to the comments above.
I tried uninstalling and installing again with no luck.

```
NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/local/lib/python3.9/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.11.0-7620-generic-x86_64-with-glibc2.33
Version: #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC 
Distribution issue: Pop!_OS 21.04 \n \l

PYTHON
======
Python version: 3.9.5

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed

```
