### ISSUE TITLE
Declare running in nautilus to shell

### ISSUE THREAD

**Issue by bersace** [flozz/nautilus-terminal#61]
Salut,

When executing a shell in e.g. Emacs or Builder, the host software declare itself using an environment variable.

What do you think of setting NAUTILUS=<something> environment variable when spawning shell ?

Bravo pour ce projet ! :fr:

**Comment by flozz** [comment]
Hello,

I just checked, the `INSIDE_NAUTILUS_PYTHON` environment variable is already declared by Nautilus Python (but the variable is empty) :)

(et merci ^^)

**Comment by bersace** [comment]
Effectivement ! Merci !
