### ISSUE TITLE
Last changes made setup.py unpackageable

### ISSUE THREAD

**Issue by TomaszGasior** [flozz/nautilus-terminal#63]
Or maybe I am just dumb enough to not understand what am I doing.  It's possible since I don't know Python at all.

I updated my RPM package with nautilus-terminal. Sorry for long delay.

I encountered some problem upgrading my RPM package from v3.4.2 to v4.0.1 because of changes in setup.py which seem to not take into account needs of packaging systems like RPM.

In my rpmspec file I invoke [`%py3_install` marco](https://github.com/TomaszGasior/mushrooms-rpms/blob/c016906e4abeb7cb93fd67ccdcabbd31549e5482/nautilus-terminal.spec#L38)  which rpmbuild from mock runs as _command_:

```
/usr/bin/python3 setup.py install -O1 --skip-build --root /builddir/build/BUILDROOT/nautilus-terminal-4.0.1-1.fc34.x86_64
```

- Current version of setup.py [requires to be ran as root](https://github.com/flozz/nautilus-terminal/blob/c1688696225c45666f7e10b201a04d70e8da99b9/setup.py#L17) to perform system-wide installation. RPM build process runs _the command_ as non-root still requiring to perform system-wide tasks.
- These tasks must be done relatively to RPM build root directory, not to the real / (as `setup.py` [seems to do](https://github.com/flozz/nautilus-terminal/blob/c1688696225c45666f7e10b201a04d70e8da99b9/nautilus_terminal/install_nautilus_extension.py#L10) now). Proper root directory seems to be specified in _the command_ as `--root` and I guess it is available in [somewhere in `self.install_data`](https://github.com/flozz/nautilus-terminal/blob/44f3a15897c104d672ad45863da17a3b37a2895b/setup.py#L19).
- Setup process installs `nautilus-terminal` installation script to the /usr/bin/. It's no-go for me since in RPM/DNF-managed systems system-wide files (except for local administrator changes) must be controlled by RPM/DNF system. The same applies for other package management mechanisms like APT/DPKG, as I understand.
- Setup process tries to compile glib schemas. In RPM this is done automatically. I can just ignore small error message non-existing `glib-compile-schemas` command but for me it's needed to keep schema compilation optional, making it possible to move this responsibility to RPM/DNF itself.

This is what I had to do for current version of my RPM package: https://github.com/TomaszGasior/mushrooms-rpms/commit/6f4ea53de8d981253321fff777841992db32347b#diff-92717c8a141b3e8dab06c8a7faa9912c38d89899f8fdac9fbe715a4dc349bdb7R39-R48 

It would be good  to find some upstream solution for this problem. Maybe I am doing something wrong in the RPM spec itself.

----

Commands to reproduce package building in Fedora:

```
git clone https://github.com/TomaszGasior/mushrooms-rpms.git
cd mushrooms-rpms
git checkout nautilus-terminal
mock --spec=nautilus-terminal.spec --sources=. -r fedora-34-x86_64
```

Output from COPR building process: https://download.copr.fedorainfracloud.org/results/tomaszgasior/mushrooms/fedora-34-x86_64/02200626-nautilus-terminal/build.log.gz

**Comment by flozz** [comment]
Thank you for your feedback. It seems I made packaging the app more difficult.... Let's try to fix this!

> Current version of setup.py requires to be ran as root to perform system-wide installation. RPM build process runs the command as non-root still requiring to perform system-wide tasks.

Yes I tried to fix installation problem for users that install Nautilus Terminal from sources, and I may forget about packaging issue it can create...

Maybe I can run the system-wide install anyway if a specific environment variable is defined?
Maybe I can also run it when the some of the `setup.py install` parameters are used (like `--root`)?

What's the best for you?


> These tasks must be done relatively to RPM build root directory, not to the real / (as setup.py seems to do now). 

In the following file, the `ROOT` variable is the folder that contains the package, and it is only used to find **source** files (and not where to install them):

* https://github.com/flozz/nautilus-terminal/blob/c1688696225c45666f7e10b201a04d70e8da99b9/nautilus_terminal/install_nautilus_extension.py#L10


> Proper root directory seems to be specified in the command as --root and I guess it is available in somewhere in self.install_data.

For now you can change the place where the data are installed by setting the `XDG_DATA_DIR` environment variable to something like:

    XDG_DATA_DIR=/builddir/build/BUILDROOT/nautilus-terminal-4.0.1-1.fc34.x86_64/usr/share

Maybe I can add more code to the `setup.py` file to automatically set the right paths when the `--root` parameter is defined?


> Setup process installs nautilus-terminal installation script to the /usr/bin/. It's no-go for me since in RPM/DNF-managed systems system-wide files (except for local administrator changes) must be controlled by RPM/DNF system. The same applies for other package management mechanisms like APT/DPKG, as I understand.

This not really intends to be an "install" script. It is more a "check / print version / print debug" command for now... with some capacity to fix a broken install ^^'... Maybe we will also be able to run the config dialog with this command later...

But you are right, the "fix broken install" part should not be available when the software is packaged!

I think that removing it is ok for now but be aware that users can still run it with the `python3 -m nautilus_terminal` command... so we must find a better solution.

As a packager, are you able to apply a patch to a source file? Maybe I can defined a global variable in a file of the package to disable the install/uninstall commands when the software is packaged?


> Setup process tries to compile glib schemas. In RPM this is done automatically. I can just ignore small error message non-existing glib-compile-schemas command but for me it's needed to keep schema compilation optional, making it possible to move this responsibility to RPM/DNF itself.

I can probably disable schema compilation with an env var too...

---

This message contains my thought while discovering your packaging issues... I will fix that mess... Please give me your feedbacks to help me making the right choices :)

**Comment by TomaszGasior** [comment]
You don't have to do anything about schema compilation. Just don't throw any exceptions, don't return non-zero when `glib-compile-schemas`. That's how it works, just keep it.

Using env vars like `XDG_DATA_DIR` for making build&install mechanism working seems to be workaround, not solution. Previous version of setup.py seemed to be somehow integrated to Python `setuptools`, using proper relative paths.

IMHO you can make setup.py run `install_system` function instead of `install_user` when `--root` is specified. I guest you can somehow get this information from `self`. Then you may pass path from `--root` into `install_system`  and, inside function, prefix all target paths with given path.

You can split installation & managing tasks from `/usr/bin/nautilus-terminal` to separate script committed to the repository with ability to be ran without installation at all, while `/usr/bin/nautilus-terminal` may be used to provide end-user features like preferences window and version information.

**Comment by TomaszGasior** [comment]
I can apply downstream patches if it's needed but this is in Fedora guidelines to work with upstream and avoid patches. I am not official packager, so I don't have to comply with official distribution guidelines. Still, less patches is good for software stability. 

I hope described solution won't be hard to do. If you find some time to implement these changes, you can push some changes into separate testing branch and let me build RPM against it to see the result. :)

**Comment by flozz** [comment]
I started working on this in the `63-improve-packaging` branch.

What is done:

* [x] A system-wide installation is performed when the install is run as `root` **OR** if the `--root` option of setuptools is used
* [x] The prefix given by the `--root` setuptools option is now used as prefix while performing system-wide install. So if you set `--root /tmp/foo` data files will be installed in `/tmp/foo/usr/share`

What I still have to do:

* [ ] Disabling the install fix commands for packaged installs... I have to find an acceptable solution here... :)

> You can split installation & managing tasks from /usr/bin/nautilus-terminal to separate script committed to the repository with ability to be ran without installation at all, while /usr/bin/nautilus-terminal may be used to provide end-user features like preferences window and version information.

This is not a good solution... as people mainly install Nautilus Terminal from PyPI (`pip install nautilus-termunal`), so they would have to also clone this repository to run the scripts...

**Comment by TomaszGasior** [comment]
> This is not a good solution... as people mainly install Nautilus Terminal from PyPI (pip install nautilus-termunal), so they would have to also clone this repository to run the scripts...

Why this script is needed at all? :)

**Comment by flozz** [comment]
I do not know why, but sometimes, users have issue where data are not automatically installed so they have to fix it manually :(

**Comment by TomaszGasior** [comment]
For now, since the script is not needed for end users to use the extension, I can just `rm` it inside rpmspec. The best solution would be to debug and revolse issues, then get rid of managing functionality from `/usr/bin/nautilus-terminal` script.

I will check your separate branch soon.

**Comment by flozz** [comment]
If it is easy for you to just remove a file from the package, I can add a `is_not_packaged.py` that can be removed by packagers... And if this file is not present I disable the `--install-*` / `--uninstall-*` commands... It would be an easy fix for now before finding a better solution :man_shrugging:

**Comment by TomaszGasior** [comment]
Ok, let's work around the problem this way. For me you need to specify what file I have to `rm`.

**Comment by flozz** [comment]
Ok, I will do this after work :)

**Comment by flozz** [comment]
I added the possibility for packagers to disable the problematic options. You just have to remove the [`nautilus_terminal/not_packaged.py`](https://github.com/flozz/nautilus-terminal/blob/63-improve-packaging/nautilus_terminal/not_packaged.py) file.

While this file is removed, the `--install-*` / `--uninstall-*` options are hidden from the help (`--help`), and if the user try to use them, a descriptive error message is displayed:

```
$ python -m  nautilus_terminal --install-user
E: You cannot perform this action:
You installed Nautilus Terminal using a distribution package. If you encounter an issue, try to reinstall it or contact its maintainer.
```

I also added some documentation about this: https://github.com/flozz/nautilus-terminal/blob/63-improve-packaging/README.rst#packaging-this-software

Can you test that everything is ok? If it works I will release this as a new version :)

**Comment by TomaszGasior** [comment]
@flozz Your changes work properly. I was able to build working RPM against your branch.

**Comment by flozz** [comment]
Nautilus Terminal **v4.0.2** released with the fixes. Thank you fro your help! :)
