### ISSUE TITLE
Copy & Paste functionality

### ISSUE THREAD

**Issue by jan-engel** [flozz/nautilus-terminal#65]
The extension is very nice, but I like to use copy & paste text. This is not working with the help of the mouse nor with the shortcuts Strg+C and Strg+V.

A copy & paste functionality would be very nice and helpful. 
Is there any way to enable it?

**Comment by flozz** [comment]
Hello,

Normally you should be able to copy/paste using the context menu (right-click on the terminal) or using the `Ctrl+Shift+C` / `Ctrl+Shift+V` shortcuts.

I do not know what the `Strg` key is, I do not have it on my Keyboard ^^'

Can you tel me which version of Nautilus Terminal you installed and how you installed it (a specific distribution package, pip, from source,...)

**Comment by jan-engel** [comment]
Hey,

I am on an arch system installing the extension using `sudo pacman -S nautilus-terminal`. The nautilus version is 40.1.
But I have the same issue on my manjaro laptop with nautilus 38. Nautilus was installed by default.

Btw a context menu isn't shown up at all.

Sorry I forgot to translate the germany keyboard, ... :)

**Comment by flozz** [comment]
Ok, it seems the `nautilus-terminal` package is not yet up to date on Arch (the package contains the 3.5.0 version and the context menu was added in the 4.0.0), and Manjaro probably use the same package so...

* https://archlinux.org/packages/community/any/nautilus-terminal/

The keyboard shortcut should work anyway, and maybe you can install Nautilus Terminal using pip until the Arch package was updated

**Comment by jan-engel** [comment]
I update the package from pip and the context menu is working now.  
The keyboard shortcuts doesn't work at all but I can live with that at the moment.
Thanks for the help.

**Comment by flozz** [comment]
Ok, I close the issue then. Open a new one if you have other questions :)
