### ISSUE TITLE
ImportError: No module named nautilus_terminal.crowbar

### ISSUE THREAD

**Issue by shmu26** [flozz/nautilus-terminal#67]
I installed nautilus_terminal as local user, on MX Linux 19 with default Xfce desktop, using:

```
pip3 install --user .
  python3 -m nautilus_terminal --install-user

```
(I chose that option because there was an error when installing system-wide. The error seems to be related to the version of pip.) 
 
The installation went okay but I get the error in the title line. 

```
shmuel@shmuelmx ~> nautilus-terminal --check
Nautilus Python: Installed
Nautilus Terminal Extension: Installed

shmuel@shmuelmx ~> python3 -m nautilus_terminal --check
Nautilus Python: Installed
Nautilus Terminal Extension: Installed

shmuel@shmuelmx ~> nautilus -q && nautilus

(nautilus:3179): Gtk-WARNING **: 09:37:34.238: Theme parsing error: colors.css:78:0: unknown @ rule
Traceback (most recent call last):
  File "/home/shmuel/.local/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar
```

I reinstalled it, this time following these instructions:

```
Ubuntu 19.10 and earlier
^^^^^^^^^^^^^^^^^^^^^^^^

To install Nautilus Terminal on Ubuntu <= 19.10, first install dependencies::

   sudo apt install python-nautilus python-psutil python-pip libglib2.0-bin dconf-editor

Then install Nautilus Terminal::

    sudo pip install nautilus-terminal
    sudo nautilus-terminal --install-system

Finally close current Nautilus instance to apply the changes::

    nautilus -q

```
It works. You can close the issue. 

By the way, the git clone instructions do not reflect the current address usage for github. You have it like this:

`git clone git@github.com:flozz/nautilus-terminal.git
`

It needs to be in this format:

`git clone https://github.com/flozz/nautilus-terminal.git`

**Comment by flozz** [comment]
Hello,

Happy to see you found a solution :)

> By the way, the git clone instructions do not reflect the current address usage for github.

You are right, I do not know why I put the SSH clone URI, the HTTP one is more appropriate here. It is now fixed, thank you :)
