### ISSUE TITLE
Problem on PopOS 21.04

### ISSUE THREAD

**Issue by flozz** [flozz/nautilus-terminal#68]
I still have this problem on PopOS 21.04
I tried everything according to the comments above.
I tried uninstalling and installing again with no luck.

```
NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/local/lib/python3.9/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.11.0-7620-generic-x86_64-with-glibc2.33
Version: #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC 
Distribution issue: Pop!_OS 21.04 \n \l

PYTHON
======
Python version: 3.9.5

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed

```

_Originally posted by @DATL4G in https://github.com/flozz/nautilus-terminal/issues/60#issuecomment-878471360_

**Comment by flozz** [comment]
Hello @DATL4G, I moved your message to a new issue to not notify people of the older one :)

* Can you please explain your exact issue? 
* Does Nautilus crashes after installing Nautilus Terminal?  
* Have you some Nautilus logs to share (type this command to have some `nautilus -q && nautilus`)

**Comment by DATL4G** [comment]
## Issue:
I already had it installed on PopOS 20.04 and 20.10 and it worked fine.
After upgrading to PopOS 21.04 it was gone and then I wanted to reinstall it (and updated the package).
Nautilus works fine without nautilus-terminal, however after installing it Nautilus crashes or won't even start.
**Caused by the schema.**
I tried rebuilding the schema and manually editing as well as deleting the schema and then reinstalling nautilus terminal but none worked.


## Logs:
#### Pip Install: 
```bash
Collecting nautilus-terminal
Using cached nautilus_terminal-4.0.2-py3-none-any.whl
Requirement already satisfied: psutil>=5.6.6 in /usr/lib/python3/dist-packages (from nautilus-terminal) (5.8.0)
Installing collected packages: nautilus-terminal
Successfully installed nautilus-terminal-4.0.2
```

#### System Install
```bash
GLib schema successfully compiled.
Nautilus Terminal extension successfully installed on the system.
```

#### Nautilus Quit
```bash
Gtk-Message: 18:42:51.796: Failed to load module "appmenu-gtk-module"
ModuleNotFoundError: No module named 'nautilus-gsconnect'
* Starting Nautilus Terminal
Initializing nautilus-image-converter extension
nautilus-wipe-Message: 18:42:52.031: Initializing
Initializing nautilus-dropbox 2020.03.04
```

#### Nautilus Start
```bash
Gtk-Message: 18:42:59.033: Failed to load module "appmenu-gtk-module"
ModuleNotFoundError: No module named 'nautilus-gsconnect'
* Starting Nautilus Terminal
Initializing nautilus-image-converter extension
nautilus-wipe-Message: 18:42:59.219: Initializing
Initializing nautilus-dropbox 2020.03.04

(org.gnome.Nautilus:9812): GLib-GIO-ERROR **: 18:42:59.373: Settings schema 'org.flozz.nautilus-terminal' does not contain a key named 'default-focus-terminal'
[1]    9812 trace trap (core dumped)  nautilus
```

**Comment by flozz** [comment]
It seems that you issue is not a missing schema but a missing key in the schema... Maybe it is not up to date. :)

Can you check that the `/usr/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml` file is identical to this one in this repository (https://github.com/flozz/nautilus-terminal/blob/master/nautilus_terminal/schemas/org.flozz.nautilus-terminal.gschema.xml)?

Can yo try to update and rebuild the Nautilus Terminal schema?

```
sudo wget -O /usr/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml https://raw.githubusercontent.com/flozz/nautilus-terminal/master/nautilus_terminal/schemas/org.flozz.nautilus-terminal.gschema.xml
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

**Comment by DATL4G** [comment]
The file is fully identical to the one in the repository.
I tried the commands and still same error.

**Comment by flozz** [comment]
Hum strange... :(

If you open dconf editor, do you see the `default-focus-terminal` key?

    dconf-editor /org/flozz/nautilus-terminal

![image](https://user-images.githubusercontent.com/971438/125677131-4e8155cd-f0ff-4be3-a320-8add9d9fe7f2.png)

**Comment by DATL4G** [comment]
No this option is missing, however i checked the file multiple times now and it's correct.

**Comment by flozz** [comment]
Is there a `~/.local/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml` file installed on your system maybe?

**Comment by DATL4G** [comment]
No there is no `glib-2.0` folder existing in `~/.local/share`

**Comment by flozz** [comment]
I really do not know what happens... I will install PopOS in a vm and try to reproduce this tomorrow

**Comment by DATL4G** [comment]
I found the old schema in `/usr/local/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml`

**Comment by flozz** [comment]
> I found the old schema in /usr/local/share/glib-2.0/schemas/org.flozz.nautilus-terminal.gschema.xml

Oh nice!

Try to remove the file and then run 

    sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas

It should fix the issue (I will update the trouble shooting section of the readme if works) :)

**Comment by DATL4G** [comment]
That worked! Thanks for helping me

**Comment by flozz** [comment]
Yeah \o/

I will update the trouble shooting doc tomorrow then :D

**Comment by j2l** [comment]
I won't upgrade to 21.04 because Ubuntu/Pop_OS! updates always fail.
Thanks for sharing your experience

**Comment by j2l** [comment]
I know it sounds harsh, but I ruined twice my OS when updating PopOS (18 to 19 and 19 to 20).
So now I wait at least 1 month and check first for issues.
Please, please PopOS, improve upgrade and support, not just pushy notifications.
I know you're not PopOS, but this issue is SEO friendly and I really hope PopOS staff simply search like their customers :)
Merci Fabien de ta compréhension :smile_cat:

**Comment by flozz** [comment]
@j2l please stop posting unrelated content to this issue. If you have something to say to the PopOS devs, contact them directly...
