### ISSUE TITLE
Terminal is not showing

### ISSUE THREAD

**Issue by bagustris** [flozz/nautilus-terminal#70]
### Bug description
Terminal is not showing

#### What happened

Terminal is not showing when pressing F4

#### What was expected

Terminal is showing when pressing F4

#### Step to reproduce

Previously, I have nautilus-terminal worked on my PC (Ubuntu 20.04).
But, after some system updates (maybe), it stops working.
I already uninstalled and reinstalled it via pip, but it doesn't work.

Installation:   
```
sudo python3.8 -m pip uninstall nautilus-terminal
sudo nautilus-terminal --install-system
```

### System information

```
bagus@m049:Datasets$ nautilus-terminal --print-debug

NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/local/lib/python3.8/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.29
Version: #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021
Distribution issue: Ubuntu 20.04.3 LTS \n \l

PYTHON
======
Python version: 3.8.10

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed


```

**Comment by flozz** [comment]
Hello,

Can you start Nautilus from a terminal to see if it outputs some errors?

    nautilus -q && nautilus

**Comment by bagustris** [comment]
Yes, I see the following error. I tried to uninstall and install the nautilus-terminal again. It didn't help.

```
bagus@m049:~$ nautilus -q
bagus@m049:~$ nautilus
Traceback (most recent call last):
  File "/home/bagus/.local/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar
<IntrospectionModule 'Nautilus' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Nautilus-3.0.typelib'>

```

**Comment by flozz** [comment]
It seems that nautilus terminal cannot be imported by python-nautilus :thinking: 

* What is the result of the following command: `python3 -c "import nautilus_terminal.crowbar"`
* Can you also try to reinstall de `python3-nautilus` package?

**Comment by bagustris** [comment]
I fixed my issue by reinstalling python3-nautilus as you suggested in the second step.
In case you need that output of the first step, this is the output of the first command

```
bagus@m049:~$ python3 -c "import nautilus_terminal.crowbar"
/usr/local/lib/python3.8/dist-packages/nautilus_terminal/crowbar.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

Thanks a lot! I will close the issue.
