### ISSUE TITLE
Minimal prompt

### ISSUE THREAD

**Issue by mellguth2** [flozz/nautilus-terminal#71]
When navigating into deeply nested folders, the command prompt of `/bin/bash` is getting quite long. It would be nice to have a simple way of setting an alternate `PS1` environment variable just for nautilus-terminal, since I already know what folder I am in from the nautilus window.
I tried using the custom shell configuration, creating a `.bashrc_minprompt` in my home folder and setting the custom shell to
`/bin/bash --rcfile /home/user/.bashrc_minprompt` , but afterwards, the terminal area just became blank with no possibility to interact with it at all (not even opening the context menu). Using `/bin/sh` does result in a minimal prompt, but it lacks a lot of features such as tab-completion.
I don't want to change the standard `.bashrc`, since I do like to have the folder in the bash prompt in regular terminals.

**Comment by flozz** [comment]
Hello,

There should be a `INSIDE_NAUTILUS_PYTHON` environment variable defined when your shell run inside Nautilus Terminal. You can use this variable to set an alternative prompt in you `.bashrc`.

Someone already had the same idea: https://github.com/flozz/nautilus-terminal/issues/34#issuecomment-570525187

:)

**Comment by mellguth2** [comment]
Thank you, the recipe from comment #34 works nicely.
