### ISSUE TITLE
There are a couple typos in the dconf settings

### ISSUE THREAD

**Issue by Pound-Hash** [flozz/nautilus-terminal#73]
### Bug description
The word **automatically** is misspelled as **automaitly**.

![image](https://user-images.githubusercontent.com/51193876/141596033-c080376d-87bd-45d0-9f6f-a8e3808acda8.png)

#### Step to reproduce

Open `dconf` settings and navigate to `/org/flozz/nautilus-terminal/`

### System information

NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/local/lib/python3.9/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
Version: #1 SMP Debian 5.10.70-1 (2021-09-30)
Distribution issue: Debian GNU/Linux 11 \n \l

PYTHON
======
Python version: 3.9.2

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed

**Comment by flozz** [comment]
Oops, I missed this typo!

Thank you for your report, this is now fixed in **Nautilus Terminal v4.0.3** :)
