### ISSUE TITLE
My terminal has spaces in it

### ISSUE THREAD

**Issue by raffaem** [flozz/nautilus-terminal#74]
### Bug description

My terminal has spaces in it:

![image](https://user-images.githubusercontent.com/54762742/146360484-eb4f986a-2b54-47b9-8c0d-ae4def7460c1.png)

#### What happened

There are spaces between the letters

#### What was expected

No space should be between letters

#### Step to reproduce

Open nautilus, but before it was ok, from some time now it is like this.

I don't know the cause.

→ 

### System information

```
$ python3 -m nautilus_terminal --print-debug

NAUTILUS TERMINAL
=================
Version: 4.0.3
System-wide extension: Installed
Current user extension: Installed
Installation path: /usr/local/lib/python3.10/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.15.6-200.fc35.x86_64-x86_64-with-glibc2.34
Version: #1 SMP Wed Dec 1 13:41:10 UTC 2021
Distribution issue: \S
Kernel \r on an \m (\l)

PYTHON
======
Python version: 3.10.0

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed
```

**Comment by flozz** [comment]
Hello,

This is not a Nautilus Terminal bug: it is the normal way VTE displays text when a non-monospace font is selected.

For example, here I selected `"Noto Mono 12"` font:
![Capture d’écran de 2021-12-16 12-43-06](https://user-images.githubusercontent.com/971438/146365779-04690a11-00cc-4a14-801c-3da59a2cd03f.png)

And here `"Noto 12"`:
![Capture d’écran de 2021-12-16 12-43-21](https://user-images.githubusercontent.com/971438/146365812-0a6a72f2-8efd-408b-8796-e686589d0286.png)

Please check the font you may configured:

    dconf-editor org.flozz.nautilus-terminal custom-font

![Capture d’écran de 2021-12-16 12-45-33](https://user-images.githubusercontent.com/971438/146366091-ad690b2c-441f-466e-8f96-f2ebd9a146d4.png)

**Comment by flozz** [comment]
NOTE: If it used to work before, maybe the configured font is no more available on your machine and it may fallback on a non-monospaced font

**Comment by raffaem** [comment]
Yeah that fixed the issue thanks.

But why the default value of that parameter is empty?

**Comment by flozz** [comment]
When it is empty, it takes the default configured font of the system. This can be configured using GNOME Tweaks tool:

    gnome-tweaks

![image](https://user-images.githubusercontent.com/971438/146367353-e71eacd7-ef92-447d-a8cf-c9de819285d5.png)

**Comment by raffaem** [comment]
Thanks.
