### ISSUE TITLE
Detect if shell is running inside nautilus terminal

### ISSUE THREAD

**Issue by jtsagata** [flozz/nautilus-terminal#77]
Provide some way, maybe an ENV variable so you can change things if running inside the embeded terminal.

Possible use: Change the color scheme

**Comment by flozz** [comment]
Hello,

There is already an `INSIDE_NAUTILUS_PYTHON` environment variable declared that you can use (see #61).

:)

**Comment by blackdaemon** [comment]
This does not work for me, this variable is not present. I am trying to avoid running termux while in the nautilus terminal so I put condition into my .bashrc to run tmux only if INSIDE_NAUTILUS_PYTHON is defined.
I also tried custom command 'INSIDE_NAUTILUS_PYTHON /bin/bash' but this also does not work, the variable is not set.
Even tried custom command 'export INSIDE_NAUTILUS_PYTHON=1; /bin/bash', also no success.

**Comment by flozz** [comment]
Maybe something has changed in Nautilus Python :shrug: 

Anyway, you can PR the change if you want :)

**Comment by flozz** [comment]
Released in **Nautilus Terminal v4.0.5**
