### ISSUE TITLE
Weird margin

### ISSUE THREAD

**Issue by ArtyomFR** [flozz/nautilus-terminal#78]
### Bug description
Weird margin in nautilus terminal

#### What happened

Open nautilus for the first time, see this:
![image](https://user-images.githubusercontent.com/20092228/174973772-794253a6-7655-4519-82dd-dfb0a4609fd0.png)
Same thing with bash by the way:
![image](https://user-images.githubusercontent.com/20092228/174972573-a6fd4fc4-4a21-419a-97ea-6af692bd1008.png)

#### What was expected
Right margin for all text element without offset:
![image](https://user-images.githubusercontent.com/20092228/174973881-fe16b210-8860-4843-a663-7927f48c0e88.png)

#### Step to reproduce
Had this bug on another setup but disapear with time (or update don't realy know).
This bug is on a complete new setup

### System information

```
❯ python3 -m nautilus_terminal --print-debug
/usr/bin/python3: No module named nautilus_terminal.__main__; 'nautilus_terminal' is a package and cannot be directly executed
```
Ok, this may be the problem....

**Comment by ArtyomFR** [comment]
Hi,
I'm using v3.5.0-2 installed from community repo with Yay.
What seems weird is that it works just fine on another laptop with quit the same setup.
Both use the default font.

**Comment by flozz** [comment]
>  I'm using v3.5.0-2 installed from community repo with Yay.

This is not the latest version (but I do not think that newer version will fix your issue)

>  Both use the default font.

It is not the same font in your Nautilus Terminal and GNOME Terminal screenshots. Maybe you can try to change the font of Nautilus Terminal to see if it fixes the issue?

To access the settings:

    dconf-editor /org/flozz/nautilus-terminal

**Comment by ArtyomFR** [comment]
There is no git package available on Arch repo to update to sadely.
Here is what happen when changing font to Liberation Sans Mono 10:
![image](https://user-images.githubusercontent.com/20092228/176367739-cd37a2a9-f683-40b0-b7ca-21a01aec0a98.png)
With default for comparison:
![image](https://user-images.githubusercontent.com/20092228/176367994-1bdf9b4d-95b2-46aa-8ad3-b4c976bef915.png)
When I said 'Both use default font' I was refering to the other setup that is plain default configuration with exact same .zshrc that had issue like this before but not anymore.

**Comment by ArtyomFR** [comment]
Issue resolved by changing nautilus-terminal font to 'Source Code Pro Regular' wich was gnome default but doesn't appear to apply.
