### ISSUE TITLE
How install on Fedora Silverblue?

### ISSUE THREAD

**Issue by cindRoberta** [flozz/nautilus-terminal#79]

**Comment by flozz** [comment]
There should be a package or Fedora, so you may follow the instructions of the README:

* https://github.com/flozz/nautilus-terminal#fedora-tomaszgasiors-package

Else you can install it from PyPI:

* https://github.com/flozz/nautilus-terminal#from-pypi

**Comment by cindRoberta** [comment]
> There should be a package or Fedora, so you may follow the instructions of the README:
> 
> * https://github.com/flozz/nautilus-terminal#fedora-tomaszgasiors-package
> 
> Else you can install it from PyPI:
> 
> * https://github.com/flozz/nautilus-terminal#from-pypi

I need find out how enable repo on rpm-ostree

**Comment by flozz** [comment]
I close the issue as there is no more activity :)
