### ISSUE TITLE
When I use backspace, nautilus go backwards

### ISSUE THREAD

**Issue by guillefix** [flozz/nautilus-terminal#8]
I can't delete a character in the terminal, because when I press the backspace key, nautilus just goes to the parent folder, and the terminal `cd`s accordingly..

**Comment by flozz** [comment]
Hello,

You installed Nautilus Terminal from this repository or from the PPA, AUR,... ?

**Comment by flozz** [comment]
Hi,

I close this issue as there is no response. Please reopen it if you have any further information :)

**Comment by guillefix** [comment]
Hi. Sorry, I uninstalled it at the end. I installed it using pip
