### ISSUE TITLE
Does not work with Nautilus 43.rc on Fedora Linux 37 beta

### ISSUE THREAD

**Issue by TomaszGasior** [flozz/nautilus-terminal#82]
I am unable to start this extension in new Nautilus ported to GTK4 on Fedora 37.  Extension is installed by my RPM package. 
[nautilus-terminal-4.0.2-1.fc37.noarch.zip](https://github.com/flozz/nautilus-terminal/files/9592326/nautilus-terminal-4.0.2-1.fc37.noarch.zip)

This is error output when launching Nautilus:

```
/usr/lib/python3.11/site-packages/nautilus_terminal/crowbar.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gi/module.py", line 263, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gi/module.py", line 110, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nautilus_terminal/crowbar.py", line 5, in <module>
    from .nautilus_terminal import create_or_update_natilus_terminal
  File "/usr/lib/python3.11/site-packages/nautilus_terminal/nautilus_terminal.py", line 14, in <module>
    from gi.repository import GLib, Gio, Gtk, Gdk, Vte, Pango  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gi/importer.py", line 144, in load_module
    raise ImportError(e)


```

### System information

```

NAUTILUS TERMINAL
=================
Version: 4.0.2
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/lib/python3.11/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.19.8-300.fc37.x86_64-x86_64-with-glibc2.36
Version: #1 SMP PREEMPT_DYNAMIC Thu Sep 8 19:14:17 UTC 2022
Distribution issue: \S
Kernel \r on an \m (\l)

PYTHON
======
Python version: 3.11.0

SYSTEM DEPENDENCIES
===================
Nautilus Python: Absent

```

**Comment by TomaszGasior** [comment]
Since you didn't use GitHub releases to publish new versions after v4.0.2 I didn't get notification from GitHub about new versions so I didn't update my RPM package. :( However, with up-to-date version of the source code the issue still occurs. 

I guess it won't be trivial to make your extension compatible with GTK4 and new Nautilus so for now I will make my package not installable with Nautilus 43.

**Comment by flozz** [comment]
> Since you didn't use GitHub releases to publish new versions after v4.0.2 I didn't get notification from GitHub about new versions so I didn't update my RPM package. :(

You are right, I will use the Github release feature in the future... if there is any future

> I guess it won't be trivial to make your extension compatible with GTK4 and new Nautilus so for now I will make my package not installable with Nautilus 43.

I will try to port Nautilus Terminal to GTK 4 once Nautilus 43 released in Ubuntu (in about a month). We will see if it is doable or if it is too complicated :)

**Comment by palto42** [comment]
Hi @flozz , just want to add that I face the same issue on Solus which was just upgraded to Gnome 43.

**Comment by flozz** [comment]
I had a look to currently available APIs ; it seems there is no obvious way to integrate Nautilus Terminal with them. 

Nautilus Terminal was never a "first class citizen" in Nautilus: it hijacked existing APIs to slip into Nautilus. It used a lot of hacks to work around limitations and to work (you can read the comments in [nautilus_terminal.py](https://github.com/flozz/nautilus-terminal/blob/master/nautilus_terminal/nautilus_terminal.py) if you're curious).

I already wrote a quite long [blog post about Nautilus Terminal](https://blog.flozz.fr/2018/12/17/nautilus-terminal-lhistoire-dun-projet-complique/) years ago where I stated that its future was unsure.

There may be some APIs in the future to integrate a terminal in Nautilus (and if that happens, everything will have to be redeveloped from scratch), but I think that for now, after 12 years of existence, it is the end of the project.

A big thanks to all users and contributors of Nautilus Terminal.

**Comment by toccata10** [comment]
hi Flozz,
This is very sad: it's my most used extension in my daily life/work: switching from graphical to command-line is awesome. Saved my hours of repetitive tasks.
So thanks a lot for making my life so much easier for such a long time.
It's so useful I can't understand why it's not a standard feature of nautilus: when you've tasted it, you just can't stop using it.
I wonder if there's any alternative as you seem pessimistic about the future of this.
Once more: thanks a lot

**Comment by flozz** [comment]
>  I wonder if there's any alternative as you seem pessimistic about the future of this.

Currently there is no alternative for Nautilus itself but there are Nautilus forks like [Caja](https://wiki.mate-desktop.org/mate-desktop/applications/caja/) and [Nemo](https://github.com/linuxmint/nemo) that may be able to integrates older (or patched) versions of Nautilus Terminal. There is also Dolphin, the KDE file manager integrates natively a terminal.

Nautilus developers are open to discussion so you may open a thread of their discourse to ask if it is possible to add APIs to integrate a terminal properly in Nautilus. :)

* https://discourse.gnome.org/tag/nautilus

**Comment by flozz** [comment]
There is currently a discussion on GNOME forums about Nautilus Terminal: 

* https://discourse.gnome.org/t/feature-request-integrate-terminal-in-nautilus-like-gnome-terminal/12296

**Comment by wood-j** [comment]
What a pitty to hear that

**Comment by tekkamanninja** [comment]
Really hope this can work on Fedora 38

**Comment by TomaszGasior** [comment]
@tekkamanninja No, this extension will not work anymore in any new version of Nautilus. nautilus-terminal relied on unsupported hacks and these hacks does not work anymore in current Nautilus, without replacements. https://github.com/flozz/nautilus-terminal/issues/89#issuecomment-1564290313
