### ISSUE TITLE
GLib-GIO-ERROR 'org.flozz.nautilus-terminal' does not contain a key named 'color-palette'

### ISSUE THREAD

**Issue by bedaberner** [flozz/nautilus-terminal#85]
### Bug description
When I start nautilus i get:
(org.gnome.Nautilus:152092): GLib-GIO-ERROR **: 10:02:46.041: Settings schema 'org.flozz.nautilus-terminal' does not contain a key named 'color-palette'

this seems to be similar to [this issue](https://github.com/flozz/nautilus-terminal/issues/60) but the I tried deleting the files and recompiling and it did not help.

I have had nautilus_terminal working before but i did some updates (both on system and in python environment) and now it doesn't work anymore.

Edit I have seen that color palette was introduced with 4.1.0, downgrading to 4.0.6 fixed the problem for me.
### System information

```
<!-- Please provide the output of the `python3 -m nautilus_terminal --print-debug` command here -->
```
NAUTILUS TERMINAL
=================
Version: 4.1.0
System-wide extension: Installed
Current user extension: Absent
Installation path: /home/beda/.local/lib/python3.8/site-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.29
Version: #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022
Distribution issue: Ubuntu 20.04.5 LTS \n \l

PYTHON
======
Python version: 3.8.10

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed

**Comment by flozz** [comment]
Is there any error when running the following command?

     sudo python3 -m nautilus_terminal --install-system 

Can you also try a reboot just a in case? :)

**Comment by bedaberner** [comment]
the command goes through without any issue
```
GLib schema successfully compiled.
Nautilus Terminal extension successfully installed on the system.
```
both before and after reboot

Edit: I just tried this [solution again](https://github.com/flozz/nautilus-terminal/issues/60#issuecomment-830816030) and it seems the first time I tried it, it might not have worked because I did not spot the typo in the given command and did not pay attention to the console output -.-

when using 
`python3 -m nautilus_terminal --install-user` instead of 
python3 -m na**uit**lus_terminal --install-user 
the given fix works.

**Comment by flozz** [comment]
Ok nice if it works.
Thank you for the feedback :)
