### ISSUE TITLE
Ubuntu14.04.5 can't installed.

### ISSUE THREAD

**Issue by bluoy** [flozz/nautilus-terminal#9]
Ubuntu14.04.5
nautilus 3.10.1
libgtk 3.10.8

some errors likes:
AttributeError: 'tuple' object has no attribute 'non_relocatable'
AttributeError: '__main__.NautilusApplication' object has no attribute 'get_accels_for_action'

**Comment by flozz** [comment]
Hello,

Ubuntu 14.04 is very old so I think it will not be possible to support it with this Nautilus Terminal version... 

You should try the old one that was maintained on Launchpad → https://launchpad.net/nautilus-terminal. It has some known bug, but there is workaround for some of them → https://answers.launchpad.net/nautilus-terminal/+question/255799

**Comment by bluoy** [comment]
thanks for your reply. I will try it.
